typography_spectrum: 0
color:
  brandColors:
    - '#030303'
    - '#b4ddef'
    - '#0e2336'
    - '#006ea3'
    - '#5b98c4'
  brandStrength: 0.1875
  lightness: 0.8924731
  saturation: 0.7741935
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.26047
analytics:
  google: UA-75482434-1
  facebook: null
  twitter: null
name: e-metadata
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About us
    url: 'http://www.e-metadata.eu/aboutus.html'
    type: external
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: e-commerce news and technical seo guidelines
purpose: []
