title: e-commerce news and technical seo guidelines
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7741935
  brandStrength: 0.1875
  rhythmicContrast: 0.5
  brandColors:
    - '#030303'
    - '#b4ddef'
    - '#0e2336'
    - '#006ea3'
    - '#5b98c4'
  lightness: 0.8924731
cta:
  bucket: null
  version: null
  domain: null
favicon: null
analytics:
  twitter: null
  google: UA-75482434-1
  facebook: null
name: e-metadata
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.2293907
layout_spectrum: 0.6630824
