name: e-metadata
favicon: null
layout_spectrum: 0.99265
typography_spectrum: 0
title: e-metadata
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030303'
    - '#b4ddef'
    - '#0e2336'
    - '#006ea3'
    - '#5b98c4'
  brandStrength: 0.125
  lightness: 0.566262876149267
  saturation: 0.5649136954452842
  rhythmicContrast: 0.4991087696980685
purpose: []
