name: e-metadata
favicon: null
layout_spectrum: 0.9522853444796056
typography_spectrum: 0.6420352363493294
title: e-metadata
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.041408037999644876
  lightness: 0.566262876149267
  saturation: 0.5649136954452842
  rhythmicContrast: 0.4991087696980685
purpose: []
