typography_spectrum: 0
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
layout_spectrum: 0.99265
title: e-metadata
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 0.5649136954452842
  brandStrength: 0.125
  rhythmicContrast: 0.4991087696980685
  brandColors:
    - '#030303'
    - '#b4ddef'
    - '#0e2336'
    - '#006ea3'
    - '#5b98c4'
  lightness: 0.566262876149267
purpose: []
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
name: e-metadata
